scrape_configs:
  - job_name: "application"
    metrics_path: "/actuator/prometheus"
    static_configs:
      # - targets: ["localhost:8080"]  # this will point to container 8080 if prometheus is run in docker
      # these can be used when running in hybrid mode
      - targets: ["host.docker.internal:8088", "mhpractice-backend:8088"]    